#!/usr/bin/env python3
"""
VELUX Active — Key Extraction Tool
====================================
Retrieves the HashSignKey (sign_key) and SignKeyId (sign_key_id) needed
to open windows via the VELUX Active Home Assistant integration.

OVERVIEW
--------
VELUX windows require two cryptographic keys to accept open/close commands
from Home Assistant. These keys are generated by your VELUX gateway and stored
inside the VELUX Active app on your iPhone. This script extracts them so you
can enter them into the Home Assistant integration settings.

═══════════════════════════════════════════════════════════════════
STEP-BY-STEP GUIDE
═══════════════════════════════════════════════════════════════════

STEP 1 — Install Python dependencies
─────────────────────────────────────
Open a terminal (Command Prompt / PowerShell on Windows, Terminal on Mac)
and run:

    pip install requests pycryptodome iphone-backup-decrypt

STEP 2 — Create an encrypted iPhone backup  ← IMPORTANT
──────────────────────────────────────────────────────────
The VELUX keys are stored in your iPhone's keychain. They can only be
extracted from an *encrypted* backup (unencrypted backups do not include
the keychain).

  On Windows (Apple Devices):
    1. Install "Apple Devices" from the Microsoft Store if you haven't already.
    2. Open Apple Devices and connect your iPhone via USB.
    3. Click your iPhone in the left sidebar.
    4. Under "Backups", select "Back up all of the data on your iPhone
       to this Windows PC".
    5. Tick "Encrypt local backup" and set a password you will remember.
    6. Click "Back Up Now" and wait for it to finish.

  On Mac (Finder):
    1. Connect your iPhone via USB and open Finder.
    2. Select your iPhone in the sidebar.
    3. Under "Backups", select "Back up all of the data on your iPhone
       to this Mac".
    4. Tick "Encrypt local backup" and set a password.
    5. Click "Back Up Now" and wait for it to finish.

  ⚠  Make sure the VELUX Active app is installed and has successfully
     paired with your gateway BEFORE making the backup. The keys are
     only written to the keychain after a successful pairing.

STEP 3 — Run this script
─────────────────────────
In the same terminal, navigate to the folder containing this file and run:

    python get_velux_keys.py

The script will:
  • Ask for your VELUX Active email and password
  • Try to retrieve keys directly from the VELUX API (fast, sometimes works)
  • If that fails, locate your iPhone backup automatically and ask for
    the backup encryption password you set in Step 2
  • Decrypt the backup keychain and search for the VELUX keys
  • Print the two values you need to copy into Home Assistant

STEP 4 — Enter the keys into Home Assistant
────────────────────────────────────────────
  1. Open Home Assistant and go to:
       Settings → Devices & Services → VELUX Active → Configure
  2. Paste the HashSignKey value into the "sign_key" field.
  3. Paste the SignKeyId value into the "sign_key_id" field.
  4. Click Submit. Home Assistant will reload the integration.
  5. Test by pressing Open on one of your VELUX windows.

═══════════════════════════════════════════════════════════════════

TROUBLESHOOTING
───────────────
• "Backup is NOT encrypted" — repeat Step 2 and tick "Encrypt local backup".
• "Wrong passphrase" — try the password you set when creating the backup.
  Note: this is separate from your Apple ID password.
• "No VELUX keys found" — ensure the backup was made AFTER the VELUX app
  paired with the gateway. Delete the old backup, re-pair the app if needed,
  then make a fresh encrypted backup.
• Keys found but windows still don't open — double-check you copied the full
  values without extra spaces, and reload the integration after saving.

If you're still stuck, open an issue at:
  https://github.com/GMounsor/velux/issues
"""

from __future__ import annotations

import base64
import getpass
import hashlib
import json
import os
import plistlib
import struct
import sys
from typing import Any


# ── dependency check ─────────────────────────────────────────────────────────

def _require(pkg: str, pip_name: str | None = None) -> Any:
    import importlib
    try:
        return importlib.import_module(pkg)
    except ImportError:
        name = pip_name or pkg
        print(f"\nERROR: '{name}' is not installed.")
        print(f"Run:   pip install {name}")
        sys.exit(1)

requests = _require("requests")


# ── VELUX API constants ───────────────────────────────────────────────────────

AUTH_URL      = "https://app.velux-active.com/oauth2/token"
HOMESDATA_URL = "https://app.velux-active.com/api/homesdata"
SETSTATE_URL  = "https://app.velux-active.com/syncapi/v1/setstate"
CLIENT_ID     = "5931426da127d981e76bdd3f"
CLIENT_SECRET = "6ae2d89d15e767ae5c56b456b452d319"

VELUX_KEYWORDS = [
    b"velux", b"netatmo", b"HashSign", b"sign_key",
    b"endToEnd", b"EndToEnd", b"kix", b"VELUX",
]


# ── helpers ───────────────────────────────────────────────────────────────────

def _norm(s: str) -> str:
    """Normalise a field name for keyword matching."""
    return s.lower().replace("_", "").replace(".", "").replace("-", "")


def _search_keys(obj: Any, prefix: str = "") -> dict:
    """Recursively search a JSON object for key-related fields."""
    found: dict = {}
    keywords = {"key", "sign", "hash", "secret", "security", "token"}
    if isinstance(obj, dict):
        for k, v in obj.items():
            full = f"{prefix}.{k}" if prefix else k
            if any(kw in _norm(k) for kw in keywords):
                found[full] = v
            found.update(_search_keys(v, full))
    elif isinstance(obj, list):
        for i, item in enumerate(obj):
            found.update(_search_keys(item, f"{prefix}[{i}]"))
    return found


def _to_b64_padded(value: str) -> str | None:
    """Return a properly padded base64 string from hex or base64 input."""
    try:
        raw = bytes.fromhex(value)
        return base64.b64encode(raw).decode()
    except Exception:
        pass
    padded = value + "=" * (-len(value) % 4)
    try:
        base64.b64decode(padded)
        return padded
    except Exception:
        pass
    return None


# ── VELUX API ─────────────────────────────────────────────────────────────────

def api_authenticate(email: str, password: str) -> str:
    resp = requests.post(
        AUTH_URL,
        data={
            "grant_type": "password",
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
            "username": email,
            "password": password,
            "scope": "velux_scopes",
            "user_prefix": "velux",
            "app_version": "791302006",
        },
        timeout=15,
    )
    data = resp.json()
    token = data.get("access_token")
    if not token:
        print(f"\n❌  Authentication failed: {data.get('error') or data.get('message') or data}")
        sys.exit(1)
    return token


def api_get_homes(token: str) -> list[dict]:
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.post(HOMESDATA_URL, headers=headers, json={}, timeout=15)
    return resp.json().get("body", {}).get("homes", [])


def api_retrieve_key(token: str, home_id: str, bridge_id: str) -> dict:
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    body = {
        "app_identifier": "app_velux",
        "home": {
            "id": home_id,
            "modules": [{"id": bridge_id, "retrieve_key": True}],
        },
    }
    resp = requests.post(SETSTATE_URL, headers=headers, json=body, timeout=20)
    return resp.json()


def try_api_method(email: str, password: str) -> tuple[str | None, str | None]:
    """
    Try to retrieve sign_key / sign_key_id from the VELUX API.
    Returns (sign_key_hex, sign_key_id_b64) or (None, None).
    """
    print("\n🔐  Authenticating with VELUX API...")
    token = api_authenticate(email, password)
    print("✅  Authenticated")

    print("🏠  Fetching home data...")
    homes = api_get_homes(token)
    if not homes:
        print("❌  No homes found.")
        return None, None

    sign_key: str | None    = None
    sign_key_id: str | None = None

    for home in homes:
        home_id   = home.get("id", "")
        home_name = home.get("name", home_id)
        modules   = home.get("modules", [])
        gateways  = [m for m in modules if m.get("type") == "NXG"]

        if not gateways:
            continue

        print(f"\n📡  Home: {home_name}")
        for gw in gateways:
            bridge_id = gw.get("id", "")
            print(f"    Calling retrieve_key for gateway {bridge_id}...")
            raw = api_retrieve_key(token, home_id, bridge_id)
            found = _search_keys(raw)

            if found:
                print("    Key-related fields in API response:")
                for field, val in found.items():
                    print(f"      {field}: {val}")
                    norm = _norm(field.split(".")[-1])
                    if "endtoendsecuritykey" in norm and "id" not in norm:
                        sign_key = str(val)
                    elif "endtoendsecuritykeyid" in norm or "signkeyid" in norm:
                        sign_key_id = _to_b64_padded(str(val))
            else:
                print("    ℹ️   No signing keys in API response (expected — keys live in the app).")

    return sign_key, sign_key_id


# ── iOS keychain decryption ───────────────────────────────────────────────────
# Full implementation matching what the VELUX iOS app stores.
# Based on Apple's backup encryption spec and tested against live backups.

def _rfc3394_unwrap(kek: bytes, wrapped: bytes) -> bytes | None:
    """AES key-unwrap (RFC 3394)."""
    n = (len(wrapped) // 8) - 1
    if n < 1 or len(wrapped) % 8 != 0:
        return None
    from Crypto.Cipher import AES
    R = [bytearray(wrapped[8*i : 8*(i+1)]) for i in range(1, n+1)]
    A = bytearray(wrapped[:8])
    for j in range(5, -1, -1):
        for i in range(n, 0, -1):
            t = (n * j + i).to_bytes(8, "big")
            xored = bytes(a ^ b for a, b in zip(A, t))
            block = xored + bytes(R[i-1])
            dec   = AES.new(kek, AES.MODE_ECB).decrypt(block)
            A        = bytearray(dec[:8])
            R[i-1]   = bytearray(dec[8:])
    if bytes(A) != b"\xa6" * 8:
        return None
    return b"".join(bytes(r) for r in R)


def _parse_keybags(data: bytes) -> list[tuple[dict, dict]]:
    """
    Parse the BackupKeyBag TLV blob.
    Returns a list of (meta, classes) tuples — one per sub-keybag.
    The first sub-keybag is for backup files; subsequent ones may be
    for the keychain (needed for keychain item decryption).
    """
    keybags: list[tuple[dict, dict]] = []
    cur_meta: dict = {}
    cur_cls:  dict = {}
    cur_cls_id: int | None = None
    i = 0
    while i + 8 <= len(data):
        tag    = data[i:i+4].decode("ascii", errors="replace")
        length = struct.unpack(">I", data[i+4:i+8])[0]
        val    = data[i+8 : i+8+length]
        i     += 8 + length

        if tag == "UUID":
            if cur_meta or cur_cls:
                keybags.append((cur_meta, cur_cls))
            cur_meta    = {"UUID": val}
            cur_cls     = {}
            cur_cls_id  = None
        elif tag == "CLAS":
            cur_cls_id = struct.unpack(">I", val)[0]
            cur_cls.setdefault(cur_cls_id, {})
        elif cur_cls_id is not None and tag in ("WRAP", "WPKY", "PBKY"):
            cur_cls[cur_cls_id][tag] = val
        else:
            cur_meta[tag] = val

    if cur_meta or cur_cls:
        keybags.append((cur_meta, cur_cls))
    return keybags


def _derive_kek(passphrase: str, meta: dict) -> bytes | None:
    """Two-step PBKDF2 KEK derivation for iOS 10.2+ encrypted backups."""
    dpsl = meta.get("DPSL")
    dpic_raw = meta.get("DPIC")
    salt = meta.get("SALT")
    iter_raw = meta.get("ITER")
    if not all([dpsl, dpic_raw, salt, iter_raw]):
        return None
    dpic = struct.unpack(">I", dpic_raw)[0]
    itr  = struct.unpack(">I", iter_raw)[0]
    pw   = passphrase.encode("utf-8")
    step1 = hashlib.pbkdf2_hmac("sha256", pw, dpsl, dpic, dklen=32)
    return   hashlib.pbkdf2_hmac("sha1",   step1, salt, itr,  dklen=32)


def _gcm_rightshift(vec: list) -> list:
    for x in range(15, 0, -1):
        c = vec[x] >> 1
        c |= (vec[x - 1] << 7) & 0x80
        vec[x] = c
    vec[0] >>= 1
    return vec


def _gcm_gf_mult(a: list, b: list) -> list:
    mask = [0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01]
    poly = [0x00, 0xe1]
    Z = [0] * 16
    V = list(a)
    for x in range(128):
        if b[x >> 3] & mask[x & 7]:
            Z = [V[y] ^ Z[y] for y in range(16)]
        bit = V[15] & 1
        V = _gcm_rightshift(V)
        V[0] ^= poly[bit]
    return Z


def _ghash(h: bytes, auth_data: bytes, data: bytes) -> bytes:
    u = (16 - len(data)) % 16
    v = (16 - len(auth_data)) % 16
    x = auth_data + b"\x00" * v + data + b"\x00" * u
    x += struct.pack(">QQ", len(auth_data) * 8, len(data) * 8)
    y = [0] * 16
    vec_h = list(h)
    for i in range(0, len(x), 16):
        block = list(x[i : i + 16])
        y = [y[j] ^ block[j] for j in range(16)]
        y = _gcm_gf_mult(y, vec_h)
    return bytes(y)


def _inc32(block: bytes) -> bytes:
    (counter,) = struct.unpack(">L", block[12:])
    return block[:12] + struct.pack(">L", counter + 1)


def _gctr(k: bytes, icb: bytes, plaintext: bytes) -> bytes:
    if not plaintext:
        return b""
    from Crypto.Cipher import AES
    ecb = AES.new(k, AES.MODE_ECB)
    cb = icb
    out = b""
    for i in range(0, len(plaintext), 16):
        cb = _inc32(cb)
        ks = ecb.encrypt(cb)
        blk = plaintext[i : i + 16]
        out += bytes(a ^ b for a, b in zip(blk, ks[: len(blk)]))
    return out


def _gcm_empty_iv(key: bytes, ct: bytes, tag: bytes) -> bytes | None:
    """
    iOS keychain backup v2/v3 decryption (dinosec format).
    GCM with an empty IV: J0 = GHASH(H, '', '') = 0x00*16.
    """
    from Crypto.Cipher import AES
    ecb = AES.new(key, AES.MODE_ECB)
    H   = ecb.encrypt(b"\x00" * 16)
    y0  = _ghash(H, b"", b"")          # = b"\x00" * 16
    pt  = _gctr(key, y0, ct)
    s   = _ghash(H, b"", ct)
    T   = bytes(a ^ b for a, b in zip(s, ecb.encrypt(y0)))
    return pt if T == tag else None


def _try_decrypt_item(item_key: bytes, enc: bytes) -> bytes | None:
    """
    Decrypt a keychain item's encrypted payload.
    iOS keychain backups use GCM with an empty IV (dinosec/iphone-dataprotection format):
      ct  = enc[:-16]
      tag = enc[-16:]
    """
    if len(enc) < 17:
        return None

    # Primary: GCM with empty IV (iOS keychain backup v2/v3)
    ct  = enc[:-16]
    tag = enc[-16:]
    pt = _gcm_empty_iv(item_key, ct, tag)
    if pt is not None:
        return pt

    # Fallback: standard GCM with 12-byte nonce (authenticated)
    if len(enc) > 28:
        from Crypto.Cipher import AES
        try:
            c  = AES.new(item_key, AES.MODE_GCM, nonce=enc[:12], mac_len=16)
            pt = c.decrypt(enc[12:-16])
            c.verify(enc[-16:])
            return pt
        except Exception:
            pass

    # Fallback: CBC with zero IV — accept only bplist/DER output
    from Crypto.Cipher import AES
    aligned = enc[: len(enc) - len(enc) % 16]
    if aligned:
        try:
            pt = AES.new(item_key, AES.MODE_CBC, b"\x00" * 16).decrypt(aligned)
            if pt[:6] in (b"bplist", b"\x30\x82", b"\x30\x81"):
                return pt
        except Exception:
            pass

    return None


def _parse_der_keychain(pt: bytes) -> dict | None:
    """
    Parse iOS keychain DER format:
      SET { SEQUENCE { UTF8String(key), value } ... }
    Used for keychain backup items on iOS 9+.
    """
    if not pt or pt[0] not in (0x30, 0x31):
        return None

    def read_len(data: bytes, i: int) -> tuple[int, int]:
        b = data[i]; i += 1
        if b & 0x80:
            n = b & 0x7f
            length = int.from_bytes(data[i : i + n], "big")
            i += n
        else:
            length = b
        return length, i

    result: dict = {}
    i = 1  # skip outer tag
    try:
        _, i = read_len(pt, i)  # skip outer length
    except Exception:
        return None

    while i < len(pt):
        if i >= len(pt) or pt[i] not in (0x30, 0x31):
            i += 1
            continue
        i += 1
        try:
            seq_len, i = read_len(pt, i)
        except Exception:
            break
        end = i + seq_len
        if end > len(pt):
            break

        # Key: must be UTF8String (0x0c)
        if i >= end or pt[i] != 0x0c:
            i = end
            continue
        i += 1
        try:
            kl, i = read_len(pt, i)
        except Exception:
            i = end; continue
        key = pt[i : i + kl].decode("utf-8", errors="replace")
        i += kl

        # Value: any ASN.1 type
        if i >= end:
            i = end; continue
        vtag = pt[i]; i += 1
        try:
            vl, i = read_len(pt, i)
        except Exception:
            i = end; continue
        raw_val = pt[i : i + vl]
        i = end  # jump to end of this SEQUENCE

        if vtag == 0x04:                       # OCTET STRING → bytes
            result[key] = raw_val
        elif vtag in (0x0c, 0x16, 0x13, 0x18, 0x1a):  # string types → str
            result[key] = raw_val.decode("utf-8", errors="replace")
        elif vtag == 0x02:                     # INTEGER
            result[key] = int.from_bytes(raw_val, "big") if raw_val else 0
        else:
            result[key] = raw_val

    return result if result else None


def _decode_item(pt: bytes) -> dict | None:
    """Parse a decrypted keychain item — bplist first, then DER."""
    try:
        return plistlib.loads(pt)
    except Exception:
        pass
    try:
        pad = pt[-1]
        if 1 <= pad <= 16:
            return plistlib.loads(pt[:-pad])
    except Exception:
        pass
    return _parse_der_keychain(pt)


def _item_contains_keyword(item: dict | bytes) -> bool:
    """Return True if any VELUX keyword appears in the item."""
    if isinstance(item, dict):
        haystack = b" ".join(
            (v if isinstance(v, bytes) else str(v).encode())
            for v in item.values()
        )
    else:
        haystack = item
    return any(kw.lower() in haystack.lower() for kw in VELUX_KEYWORDS)


def extract_keys_from_keychain(keychain: dict, class_keys: dict) -> tuple[str | None, str | None]:
    """
    Decrypt every keychain item and return the VELUX signing key pair.

    The VELUX app stores four items under svce='endToEndSecurityKeychainServiceName':
      acct='endToEndSecurityKey<gw_id>'        → 32-byte HMAC signing key  ← sign_key
      acct='endToEndSecurityKeyId<gw_id>'      → 16-byte key ID            ← sign_key_id
      acct='endToEndSecurityPrivateKey<gw_id>' → 32-byte EC private key    (E2E encryption, not sign_key)
      acct='endToEndSecurityPublicKey<gw_id>'  → 32-byte EC public key     (E2E encryption, not sign_key)

    Returns (sign_key_hex, sign_key_id_b64) or (None, None).
    """
    sign_key:    str | None = None
    sign_key_id: str | None = None

    n_total = n_long = n_valid_klen = n_has_ck = n_unwrapped = n_decrypted = n_parsed = 0

    def _str(v: object) -> str:
        return v.decode("utf-8", errors="replace") if isinstance(v, bytes) else str(v) if v else ""

    for section in ("genp", "inet", "keys", "cert"):
        for item in keychain.get(section, []):
            vd = item.get("v_Data", b"")
            n_total += 1
            if len(vd) < 52:
                continue
            n_long += 1

            cls  = struct.unpack_from("<I", vd, 4)[0]
            klen = struct.unpack_from("<I", vd, 8)[0]
            if klen > 200 or 12 + klen > len(vd):
                continue
            n_valid_klen += 1

            ck = class_keys.get(cls)
            if ck is None:
                continue
            n_has_ck += 1

            item_key = _rfc3394_unwrap(ck, vd[12 : 12 + klen])
            if item_key is None:
                continue
            n_unwrapped += 1

            pt = _try_decrypt_item(item_key, vd[12 + klen:])
            if pt is None:
                continue
            n_decrypted += 1

            inner = _decode_item(pt)
            if inner is None:
                continue
            n_parsed += 1

            svce = _str(inner.get("svce") or inner.get("srvr") or b"")
            acct = _str(inner.get("acct") or b"")

            # Only the VELUX end-to-end security service contains our keys
            if "endToEndSecurityKeychainServiceName" not in svce:
                continue

            v_data = inner.get("v_Data") or inner.get("data")
            if not isinstance(v_data, bytes):
                continue

            norm_acct = _norm(acct)

            if "keyid" in norm_acct and sign_key_id is None:
                # endToEndSecurityKeyId<gw_id> → 16-byte key ID
                if len(v_data) == 16:
                    sign_key_id = base64.b64encode(v_data).decode()

            elif "privatek" not in norm_acct and "publickey" not in norm_acct \
                    and "keyid" not in norm_acct and sign_key is None:
                # endToEndSecurityKey<gw_id> → 32-byte HMAC signing key
                if len(v_data) == 32:
                    sign_key = v_data.hex()

            if sign_key and sign_key_id:
                break
        if sign_key and sign_key_id:
            break

    if sign_key:
        print(f"    ✅  HashSignKey (sign_key):    {sign_key}")
    if sign_key_id:
        print(f"    ✅  SignKeyId   (sign_key_id): {sign_key_id}")

    print(f"    Diagnostics: total={n_total} len≥52={n_long} valid_klen={n_valid_klen} "
          f"has_classkey={n_has_ck} unwrapped={n_unwrapped} decrypted={n_decrypted} parsed={n_parsed}")

    return sign_key, sign_key_id


def try_ios_method() -> tuple[str | None, str | None]:
    """
    Extract sign_key / sign_key_id from an encrypted iPhone backup.
    Returns (sign_key_hex, sign_key_id_b64) or (None, None).
    """
    # Check for pycryptodome
    try:
        from Crypto.Cipher import AES  # noqa: F401
    except ImportError:
        print("\n❌  pycryptodome is not installed.")
        print("    Run: pip install pycryptodome")
        return None, None

    # ── find backup ───────────────────────────────────────────────────────────
    candidates = []
    if sys.platform == "win32":
        for root in (
            os.environ.get("APPDATA", ""),
            os.environ.get("USERPROFILE", ""),
        ):
            for sub in ("Apple Computer\\MobileSync\\Backup", "Apple\\MobileSync\\Backup"):
                candidates.append(os.path.join(root, sub))
    else:
        candidates.append(os.path.expanduser("~/Library/Application Support/MobileSync/Backup"))

    backup_root: str | None = None
    for c in candidates:
        if os.path.isdir(c):
            backup_root = c
            break

    if not backup_root:
        print("\n❌  No iPhone backup directory found.")
        print("    Create an encrypted backup using Apple Devices (Windows) or Finder (Mac),")
        print("    then re-run this script.")
        return None, None

    backups = [(e.name, e.path) for e in os.scandir(backup_root) if e.is_dir()]
    if not backups:
        print(f"\n❌  No backups found in:\n    {backup_root}")
        return None, None

    print(f"\n📱  Found {len(backups)} backup(s):")
    for i, (dev, _) in enumerate(backups):
        print(f"    [{i+1}] {dev}")

    if len(backups) == 1:
        _, backup_path = backups[0]
    else:
        try:
            idx = int(input("\n    Select backup number: ").strip()) - 1
            _, backup_path = backups[idx]
        except (ValueError, IndexError):
            print("❌  Invalid selection.")
            return None, None

    passphrase = getpass.getpass("\n    Backup encryption passphrase: ")

    # ── load and parse keybag ─────────────────────────────────────────────────
    print("\n🔓  Decrypting backup keybag...")
    manifest_path = os.path.join(backup_path, "Manifest.plist")
    if not os.path.exists(manifest_path):
        print(f"❌  Manifest.plist not found in:\n    {backup_path}")
        return None, None

    with open(manifest_path, "rb") as f:
        manifest = plistlib.load(f)

    if not manifest.get("IsEncrypted"):
        print("❌  This backup is NOT encrypted.")
        print("    Create a new backup with 'Encrypt local backup' enabled.")
        return None, None

    raw_keybag = bytes(manifest["BackupKeyBag"])
    all_keybags = _parse_keybags(raw_keybag)
    print(f"    Found {len(all_keybags)} keybag(s) in backup")

    # Collect DPSL/DPIC/SALT/ITER from first keybag (global metadata)
    global_meta: dict = {}
    for meta, _ in all_keybags:
        for k in ("DPSL", "DPIC", "SALT", "ITER"):
            if k in meta and k not in global_meta:
                global_meta[k] = meta[k]

    kek = _derive_kek(passphrase, global_meta)
    if kek is None:
        print("❌  Could not derive encryption key. Check your passphrase.")
        return None, None
    print("    Key derived from passphrase ✅")

    # ── unwrap class keys — merge across ALL sub-keybags ─────────────────────
    # The BackupKeyBag contains multiple sub-keybags (one per protection class).
    # Each sub-keybag has 1 class key. We must merge them all so that every
    # class ID is available when we decrypt keychain items.
    merged_class_keys: dict = {}
    for kb_idx, (_, classes) in enumerate(all_keybags):
        for cls_id, fields in classes.items():
            wpky = fields.get("WPKY")
            if wpky and cls_id not in merged_class_keys:
                ck = _rfc3394_unwrap(kek, wpky)
                if ck:
                    merged_class_keys[cls_id] = ck
        print(f"    Keybag [{kb_idx}]: classes={sorted(classes.keys())} "
              f"({'unwrapped' if any(_rfc3394_unwrap(kek, f.get('WPKY', b'')) for f in classes.values() if f.get('WPKY')) else 'failed'})")

    print(f"    Total class keys unwrapped: {len(merged_class_keys)} "
          f"(IDs: {sorted(merged_class_keys.keys())})")

    if not merged_class_keys:
        print("❌  No class keys could be unwrapped. Wrong passphrase?")
        return None, None

    # ── extract and parse the keychain ───────────────────────────────────────
    print("\n🔍  Extracting keychain from backup...")
    try:
        from iphone_backup_decrypt import EncryptedBackup
        tmp_keychain = os.path.join(backup_path, "_velux_keychain_tmp.plist")
        backup = EncryptedBackup(backup_directory=backup_path, passphrase=passphrase)
        backup.extract_file(
            relative_path="keychain-backup.plist",
            domain_like="KeychainDomain",
            output_filename=tmp_keychain,
        )
        with open(tmp_keychain, "rb") as f:
            keychain = plistlib.load(f)
        os.remove(tmp_keychain)
    except ImportError:
        print("❌  iphone-backup-decrypt is not installed.")
        print("    Run: pip install iphone-backup-decrypt")
        return None, None
    except Exception as err:
        print(f"❌  Failed to extract keychain: {err}")
        return None, None

    counts = {s: len(keychain.get(s, [])) for s in ("genp", "inet", "keys", "cert")}
    print(f"    Keychain items: {counts}")

    print("\n🔑  Scanning for VELUX signing keys...")
    sign_key, sign_key_id = extract_keys_from_keychain(keychain, merged_class_keys)

    return sign_key, sign_key_id


# ── output ────────────────────────────────────────────────────────────────────

def print_ha_config(sign_key: str, sign_key_id: str) -> None:
    print()
    print("=" * 60)
    print("🎉  Keys found — add these to Home Assistant:")
    print("=" * 60)
    print()
    print("  Go to:  Settings → Devices & Services")
    print("          → VELUX Active → Configure")
    print()
    print(f"  HashSignKey  (sign_key)    :")
    print(f"    {sign_key}")
    print()
    print(f"  SignKeyId    (sign_key_id) :")
    print(f"    {sign_key_id}")
    print()
    print("  Both fields are required for windows to open.")
    print("=" * 60)


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print("=" * 60)
    print("  VELUX Active — Key Extraction Tool")
    print("=" * 60)
    print()
    print("Enter your VELUX Active app credentials")
    print("(same email and password as the VELUX app):")
    print()
    email    = input("Email   : ").strip()
    password = getpass.getpass("Password: ")

    # ── Step 1: try the VELUX API ─────────────────────────────────────────────
    print("\n─── Step 1: Try VELUX API ───────────────────────────────────")
    sign_key, sign_key_id = try_api_method(email, password)

    if sign_key and sign_key_id:
        print_ha_config(sign_key, sign_key_id)
        return

    print("\n  The API did not return signing keys directly.")
    print("  This is normal — keys are stored inside the VELUX app on your phone.")

    # ── Step 2: extract from iPhone backup ───────────────────────────────────
    print("\n─── Step 2: Extract from iPhone backup ──────────────────────")
    print()
    print("  Required: an encrypted iPhone backup (Apple Devices on Windows,")
    print("  Finder on Mac) with the VELUX Active app installed.")
    print()
    print("  Don't have one yet? Steps to create:")
    print("    Windows: Open Apple Devices (Microsoft Store) → connect iPhone")
    print("             → tick 'Encrypt local backup' → Back Up Now")
    print("    Mac:     Open Finder → select iPhone → tick 'Encrypt local backup'")
    print("             → Back Up Now")
    print()

    has_backup = input("  Do you have an encrypted iPhone backup? [y/N]: ").strip().lower()
    if has_backup != "y":
        print()
        print("  Re-run this script after creating an encrypted backup.")
        return

    # Ensure libraries are available
    missing = []
    for pkg, pip_pkg in [("Crypto", "pycryptodome"), ("iphone_backup_decrypt", "iphone-backup-decrypt")]:
        try:
            __import__(pkg)
        except ImportError:
            missing.append(pip_pkg)

    if missing:
        print()
        print("  Install required libraries first:")
        print(f"    pip install {' '.join(missing)}")
        return

    sign_key, sign_key_id = try_ios_method()

    if sign_key and sign_key_id:
        print_ha_config(sign_key, sign_key_id)
        return

    # ── Step 3: not found ─────────────────────────────────────────────────────
    print()
    print("─── Keys not found ──────────────────────────────────────────")
    print()
    print("  The automatic extraction could not locate the VELUX signing keys.")
    print("  This can happen if:")
    print("    • The VELUX app has not completed its initial setup / sync")
    print("    • The backup was made before the VELUX app paired with the gateway")
    print("    • The keychain field name has changed in a newer app version")
    print()
    print("  Please open an issue at:")
    print("    https://github.com/GMounsor/velux/issues")
    print()
    print("  Include the output above so we can update the script.")


if __name__ == "__main__":
    main()
